##### alternatively run sageturner deploy -a artifact.pt -c predict.py ### dockerfiles are handled for you 
### sageturner deploy -c config.yaml 
#### an easy mode config 
name: CLIP-Sagemaker # name for the model you wish to deploy; this will be used to name your Sagemaker resources 
artefact: path/to/x.pt # model artifact; gets put on S3 and then loaded into /opt/model by sagemaker
predict-code: predict.py:
docker-dir: path/to/dir/with/Dockerfile # path to dockerfile; cannot be used with predict code 
sagemaker:
  bucket: /name/of/custom/bucket #create if not exist
  role: /name/of/custome/role  # create if not exist 
compute: 
  gpu: true
  memory: 
  cpu: 
  max_concurrency: 