[package]
name = "simplesage"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.13"
aws-config = "1.5.16"
aws-sdk-sagemaker = "1.101.0"
bollard = "0.18.1"
futures-util = "0.3.31"
tar = "0.4.43"
tempfile = "3.16.0"
tokio = { version = "1.43.0", features = ["full"] }
